# Generated by Django 3.1.3 on 2020-12-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120)),
                ('company_name', models.CharField(max_length=120)),
                ('job_title', models.CharField(max_length=120)),
                ('skills', models.CharField(max_length=120)),
                ('experience', models.CharField(max_length=120)),
                ('job_details', models.TextField(max_length=250)),
                ('phonenumber', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=50)),
                ('locatns', models.CharField(default='', max_length=120)),
                ('dateposted', models.DateTimeField(default='Fri Dec 18 00:00:00 2020')),
            ],
        ),
        migrations.CreateModel(
            name='employerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=120)),
                ('company_name', models.CharField(max_length=120)),
                ('job_details', models.TextField(max_length=350)),
                ('phonenumber', models.CharField(max_length=120)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(default='', max_length=15)),
                ('qualification', models.TextField(max_length=500)),
                ('job_experience', models.TextField(max_length=500)),
                ('upload_resume', models.FileField(upload_to='documents/')),
                ('profile_pic', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
