# Generated by Django 3.1.3 on 2020-12-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField()),
                ('qualification', models.TextField(max_length=500)),
                ('job_experience', models.TextField(max_length=500)),
                ('upload_resume', models.FileField(upload_to='documents')),
            ],
        ),
    ]
