# Generated by Django 3.1.3 on 2020-12-18 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201218_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjob',
            name='dateposted',
            field=models.DateField(verbose_name=datetime.date(2020, 12, 18)),
        ),
    ]
