# Generated by Django 3.1.3 on 2020-12-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='employerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120)),
                ('job_details', models.CharField(max_length=120)),
                ('phonenumber', models.CharField(max_length=120)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='upload_resume',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
