# Generated by Django 3.1.3 on 2020-12-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201212_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='password',
        ),
    ]
