# Generated by Django 3.1.3 on 2020-12-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_employerprofile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='addJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120)),
                ('job_details', models.TextField(max_length=250)),
                ('phonenumber', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=50)),
            ],
        ),
    ]
