# Generated by Django 3.1.3 on 2020-12-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_addjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='addjob',
            name='user',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='user',
            field=models.CharField(default='', max_length=120),
        ),
    ]
