# Generated by Django 3.1.3 on 2020-12-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20201213_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='addjob',
            name='experience',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='addjob',
            name='job_title',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='addjob',
            name='skills',
            field=models.CharField(default='', max_length=120),
        ),
    ]
