# Generated by Django 3.1.3 on 2020-12-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20201213_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='addjob',
            name='date_posted',
            field=models.DateField(default=''),
        ),
    ]
