# Generated by Django 3.1.3 on 2020-12-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_addjob_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjob',
            name='date_posted',
            field=models.DateField(),
        ),
    ]
