# Generated by Django 3.1.3 on 2020-12-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20201215_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjob',
            name='date_posted',
            field=models.DateField(default=''),
        ),
    ]
